import Enum from '@/enums/Enum'

export default Enum({
  ADD_PREVENT_SETTINGS_CLOSE: 'BA__ADD_PREVENT_SETTINGS_CLOSE',
  REMOVE_PREVENT_SETTINGS_CLOSE: 'BA__REMOVE_PREVENT_SETTINGS_CLOSE',
  SET_SETTINGS_SECTION: 'BA__SET_SETTINGS_SECTION'
})
