import Enum from '@/enums/Enum'

export default Enum({
  Element: 'element',
  Hast: 'hast',
  Container: 'container',
  AnimeStagger: 'anime.stagger',
  AnimeTimeline: 'anime.timeline',
  AnimeRandom: 'anime.random',
  AnimeGet: 'anime.get',
  AnimeSet: 'anime.set',
  AnimePath: 'anime.path',
  Duration: 'duration',
  Easing: 'easing',
  Variant: 'variant',
  Position: 'position',
  Direction: 'direction',
  Module: 'module',
  Type: 'type',
  ObjectAssign: 'Object.assign',
  Wait: 'wait',
  StringTemplate: 'string.template',
  Math: 'math',
  StyleRemoveProperty: 'style.removeProperty',
  Undefined: 'undefined',
  Function: 'function',
  Arguments: 'arguments',
  Debug: 'debug',
  VarGet: 'var.get',
  VarSet: 'var.set'
})
